services:
  postgres:
    image: postgres:16
    container_name: postgres
    hostname: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: metabase_db
      POSTGRES_PASSWORD: root
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    networks:
      - metanet1
    volumes:
      - postgres:/var/lib/postgresql/data
    # build:
    #   context: ./postgres
    #   dockerfile: Dockerfile

  metabase:
    platform: linux/x86_64
    image: metabase/metabase
    container_name: metabase
    hostname: metabase
    volumes:
      - metabase:/metabase.db:cached
    ports:
      - 3000:3000
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase_db
      MB_DB_PORT: 5432
      MB_DB_USER: postgres
      MB_DB_PASS: root
      MB_DB_HOST: postgres
      MB_DB_CONNECTION_URI: jdbc:postgresql://postgres:5432/metabase_db?user=postgres&password=root

    networks:
      - metanet1
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 30s
      timeout: 10s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 6g

  python-app:
    build:
      context: ./python-app
      dockerfile: Dockerfile
    container_name: python-app
    hostname: python-app
    depends_on:
      - metabase
    networks:
      - metanet1
    entrypoint: ["sh", "-c", "while ! nc -z metabase 3000; do sleep 1; done; streamlit run app.py --server.port 8080"]
    ports:
      - 8080:8080
    #portが必要かも

volumes:
  postgres:
  metabase:

networks:
  metanet1:
    driver: bridge
